services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - ./.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus
      - ./sre-configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    ports:
      - '8080:8080'
    env_file:
      - ./backend/.env

  bot:
    container_name: bot
    build:
      context: ./kaiteki-bot
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file:
      - ./kaiteki-bot/.env

volumes:
  grafana-data:
  prometheus-data:
