version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    ports:
      - '8080:8080'
    env_file:
      - ./backend/.env
