services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    ports:
      - '8080:8080'
    env_file:
      - ./backend/.env

  bot:
    container_name: bot
    build:
      context: ./kaiteki-bot
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file:
      - ./kaiteki-bot/.env

volumes:
  grafana-data:
