version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=kaiteki
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb:/data/db
    networks:
      - app-network
    ports:
      - '27017:27017'

volumes:
  mongodb:

networks:
  app-network:
    driver: bridge