import { ChangeDetectionStrategy, Component } from '@angular/core'

import { Observable, of } from 'rxjs'

@Component({
	selector: 'app-playlist-songs',
	templateUrl: './playlist-songs.component.html',
	styleUrls: ['./playlist-songs.component.scss'],
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlaylistSongsComponent {
	// TODO: Change the any type to specific interface
	songs$: Observable<any[]> = of([
		{
			id: 1,
			song: 'Wanna be yours',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 207,
		},
		{
			id: 2,
			song: '505',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 280,
		},
		{
			id: 3,
			song: 'Do i wanna know?',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 196,
		},
		{
			id: 4,
			song: 'Only one who knows',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 300,
		},
		{
			id: 1,
			song: 'Wanna be yours',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 207,
		},
		{
			id: 2,
			song: '505',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 280,
		},
		{
			id: 3,
			song: 'Do i wanna know?',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 196,
		},
		{
			id: 4,
			song: 'Only one who knows',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 300,
		},
		{
			id: 1,
			song: 'Wanna be yours',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 207,
		},
		{
			id: 2,
			song: '505',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 280,
		},
		{
			id: 3,
			song: 'Do i wanna know?',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 196,
		},
		{
			id: 4,
			song: 'Only one who knows',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 300,
		},
		{
			id: 1,
			song: 'Wanna be yours',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 207,
		},
		{
			id: 2,
			song: '505',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 280,
		},
		{
			id: 3,
			song: 'Do i wanna know?',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 196,
		},
		{
			id: 4,
			song: 'Only one who knows',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 300,
		},
		{
			id: 1,
			song: 'Wanna be yours',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 207,
		},
		{
			id: 2,
			song: '505',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 280,
		},
		{
			id: 3,
			song: 'Do i wanna know?',
			artist: 'Artic Monkeys',
			album: 'AM',
			createdAt: '2013',
			duration: 196,
		},
		{
			id: 4,
			song: 'Only one who knows',
			artist: 'Artic Monkeys',
			album: 'Favourite Worst Nightmare',
			createdAt: '2016',
			duration: 300,
		},
	])
}
